firstName = input("Cual es el nombre del primer integrante? ")
lastName = input("Cual es el apellido del primer integrante? ")
secondName = input("Cual es el nombre del segundo integrante? ")
lastNametwo = input("Cual es el apellido del segundo integrante? ")
print("Hola " + firstName, lastName + " Y "+ secondName, lastNametwo +" !!! ")
